In [1]:
import numpy as np
import math
import random

from utils import *
from Convolutional import *

In [2]:
data_01 = [1, 0, 1, 1, 1, 0, 0]
kern_3_2 = [[1, 1, 1], [1, 1, 0]]

In [3]:
outp_01 = convolutional_encode(data_01, kern_3_2)

In [4]:
outp_01

[1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1]

In [5]:
len(outp_01)

14

In [6]:
len(data_01)

7

In [7]:
data_01 = np.array(data_01)
kern_3_2 = np.array(kern_3_2)

In [8]:
outp_02 = convolutional_encode_np(data_01, kern_3_2)

In [9]:
outp_02

array([1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1])

In [10]:
outp_02.dtype

dtype('int32')

In [11]:
outp_02.dtype == int

True

In [12]:
vtr_3_2 = viterbi_transition_graph(kern_3_2)

In [13]:
vtr_3_2

{0: {0: array([0, 0], dtype=int32), 1: array([1, 0], dtype=int32)},
 1: {0: array([1, 1], dtype=int32), 1: array([0, 1], dtype=int32)},
 2: {0: array([1, 1], dtype=int32), 1: array([0, 1], dtype=int32)},
 3: {0: array([0, 0], dtype=int32), 1: array([1, 0], dtype=int32)}}

In [14]:
kern_5_2 = [[1, 0, 1, 0, 1], [1, 0, 1, 1, 0]]
kern_5_2 = np.array(kern_5_2)

In [15]:
vtr_5_2 = viterbi_transition_graph(kern_5_2)

In [16]:
kern_4_2 = [[1, 0, 1, 0], [0, 1, 1, 1]]
kern_4_2 = np.array(kern_4_2)

In [17]:
vtr_4_2 = viterbi_transition_graph(kern_4_2)

In [18]:
vtr_4_2

{0: {0: array([0, 0], dtype=int32), 1: array([0, 1], dtype=int32)},
 1: {0: array([1, 1], dtype=int32), 1: array([1, 0], dtype=int32)},
 2: {0: array([0, 1], dtype=int32), 1: array([0, 0], dtype=int32)},
 3: {0: array([1, 0], dtype=int32), 1: array([1, 1], dtype=int32)},
 4: {0: array([1, 0], dtype=int32), 1: array([1, 1], dtype=int32)},
 5: {0: array([0, 1], dtype=int32), 1: array([0, 0], dtype=int32)},
 6: {0: array([1, 1], dtype=int32), 1: array([1, 0], dtype=int32)},
 7: {0: array([0, 0], dtype=int32), 1: array([0, 1], dtype=int32)}}

In [19]:
data_02 = [1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0]

In [20]:
data_02 = np.array(data_02)

In [21]:
data_02a = [1, 1, 0, 0, 1, 0, 0, 1]

In [22]:
data_02a = np.array(data_02a)

In [23]:
data_02a_ec_5_2 = convolutional_encode_np(data_02a, kern_5_2)

In [24]:
print(data_02a_ec_5_2)

[1 0 1 1 1 0 1 1 0 1 1 0 1 1 1 0]


In [25]:
data_02_ec_3_2 = convolutional_encode_np(data_02, kern_3_2)

In [26]:
data_02_ec_3_2

array([1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0])

In [27]:
data_02_dc_3_2 = viterbi_decode_convolutional(data_02_ec_3_2, 2, 3, vtr_3_2)

In [28]:
data_02_dc_3_2 == data_02

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [29]:
# now simulate error
data_02_ec_3_2_err = np.copy(data_02_ec_3_2)
data_02_ec_3_2_err[5] = 1 - data_02_ec_3_2_err[5]
data_02_ec_3_2_err[14] = 1 - data_02_ec_3_2_err[14]

In [30]:
data_02_dc_3_2_a = viterbi_decode_convolutional(data_02_ec_3_2_err, 2, 3, vtr_3_2)

In [31]:
data_02_dc_3_2_a == data_02

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [32]:
data_02_ec_5_2 = convolutional_encode_np(data_02, kern_5_2)
data_02_dc_5_2 = viterbi_decode_convolutional(data_02_ec_5_2, 2, 5, vtr_5_2)

In [33]:
data_02_dc_5_2 == data_02

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [34]:
type(data_02_dc_5_2)

numpy.ndarray

In [45]:
data_03 = [0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0]
data_03 = np.array(data_03)

In [46]:
convcoder = ConvCode(kern_5_2)

In [47]:
# encode
data_03_coded = convcoder.encode(data_03)

In [48]:
data_03_coded

array([0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [49]:
err_ct = 4
err_locations = [int(random.random() * len(data_03_coded)) for i in range(err_ct)]

In [50]:
err_locations

[21, 46, 37, 21]

In [51]:
# simulate errors
received = np.copy(data_03_coded)
for eloc in err_locations:
    newbit = 1 - received[eloc]
    received[eloc] = newbit

In [52]:
received

array([0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1])

In [53]:
# decode
decoded = convcoder.decode(received)

In [54]:
decoded == data_03

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])